"""Obsidian bidirectional view emitter (Track 2 §2.4).

Regenerates two auto-managed blocks inside each registry project's Obsidian
page:

  - ## Sessions   (one line per SessionRecord whose
                   classification.canonical_project == project.id)
  - ## Task tree  (only when the project entry carries a `tasks:` block —
                   currently just `sessionmanager` per §2.8)

Blocks are wrapped in BEGIN/END HTML comments so hand-authored page content
stays untouched across reruns. Pages without an obsidian_page field (or with
one that doesn't exist on disk) are skipped — we do NOT create project pages
automatically per the spec.

Called from link_project's --emit-obsidian path.
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Iterable

from .. import projects as projmod
from ..record import SessionRecord
from ..store import SessionStore


VAULT_ROOT = Path("~/_/").expanduser()

SRC_ICON = {
    "claude-code": "🤖",
    "openclaw": "🦀",
    "codex": "🧠",
    "langfuse": "📈",
    "chatgpt-export": "💬",
    "claude-export": "💬",
}

STATUS_EMOJI = {
    "done": "✅",
    "completed": "✅",
    "in_progress": "🚧",
    "blocked": "⛔",
    "pending": "⏳",
}

_BEGIN = "<!-- SessionSkills:auto BEGIN {} -->"
_END = "<!-- SessionSkills:auto END {} -->"


def _fmt_date(iso: str | None) -> str:
    return iso[:10] if iso else "????-??-??"


def _session_row(rec: SessionRecord, page_path: Path) -> str:
    cls = rec.classification or {}
    paths = rec.paths or {}
    icon = SRC_ICON.get(rec.source, "·")
    slug = cls.get("topic_slug") or rec.source_id[:12]
    date = _fmt_date(rec.started_at)
    sid_short = rec.source_id[:8]
    analyzed_md = paths.get("analyzed_md")
    if analyzed_md and Path(analyzed_md).exists():
        rel = os.path.relpath(analyzed_md, page_path.parent).replace(" ", "%20")
        return f"- {date} {icon} [{slug}]({rel}) — `{sid_short}`"
    return f"- {date} {icon} {slug} — `{sid_short}`"


def _render_sessions(records: list[SessionRecord], page_path: Path) -> str:
    if not records:
        return ""
    records = sorted(records, key=lambda r: r.started_at or "", reverse=True)
    lines = [
        "## Sessions",
        "",
        "_Auto-generated by SessionSkills — edits in this block are overwritten._",
        "",
    ]
    lines.extend(_session_row(r, page_path) for r in records)
    return "\n".join(lines) + "\n"


def _render_task_tree(project: projmod.Project) -> str:
    if not project.tasks:
        return ""

    def walk(nodes: Iterable[dict[str, Any]], depth: int = 0) -> list[str]:
        out: list[str] = []
        for t in nodes:
            indent = "  " * depth
            name = t.get("name") or t.get("id", "?")
            status = t.get("status")
            glyph = STATUS_EMOJI.get(status, "") if status else ""
            trailing: list[str] = []
            if glyph:
                completed = t.get("completed_at")
                trailing.append(f"{glyph} {completed}" if completed else glyph)
            sids: list[str] = []
            for s in (t.get("session_ids") or []):
                if s:
                    sids.append(str(s))
            sid_single = t.get("session_id")
            if sid_single and sid_single not in sids:
                sids.append(str(sid_single))
            for sid in sids:
                trailing.append(f"`{sid[:8]}`")
            tail = (" — " + " · ".join(trailing)) if trailing else ""
            out.append(f"{indent}- **{name}**{tail}")
            children = t.get("children") or []
            if children:
                out.extend(walk(children, depth + 1))
        return out

    return "## Task tree\n\n" + "\n".join(walk(project.tasks)) + "\n"


def _splice_block(text: str, name: str, content: str) -> str:
    begin = _BEGIN.format(name)
    end = _END.format(name)
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end),
        re.DOTALL,
    )
    block = f"{begin}\n{content.rstrip()}\n{end}"
    if pattern.search(text):
        return pattern.sub(block, text)
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + block + "\n"


def _remove_block(text: str, name: str) -> str:
    begin = _BEGIN.format(name)
    end = _END.format(name)
    pattern = re.compile(
        r"\n*" + re.escape(begin) + r".*?" + re.escape(end) + r"\n*",
        re.DOTALL,
    )
    return pattern.sub("\n", text)


def emit_all(store: SessionStore, cfg: dict) -> int:
    """Refresh auto blocks on every registered project page. Returns count written."""
    registry = projmod.load_registry(force=True)
    if not registry:
        return 0

    by_project: dict[str, list[SessionRecord]] = {}
    for rec in store.iter_with_canonical_project():
        pid = (rec.classification or {}).get("canonical_project")
        if pid:
            by_project.setdefault(pid, []).append(rec)

    written = 0
    for p in registry:
        if not p.obsidian_page:
            continue
        page = VAULT_ROOT / p.obsidian_page
        if not page.is_file():
            continue

        recs = by_project.get(p.id, [])
        sessions_block = _render_sessions(recs, page)
        tasks_block = _render_task_tree(p)

        text = page.read_text()
        original = text
        text = (_splice_block(text, "Sessions", sessions_block)
                if sessions_block else _remove_block(text, "Sessions"))
        text = (_splice_block(text, "Task tree", tasks_block)
                if tasks_block else _remove_block(text, "Task tree"))
        if text != original:
            page.write_text(text)
            written += 1

    return written
